version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 9090:9090
    depends_on:
      - db
    environment:
      - 'MYSQL_PORT=3306'
      - 'MYSQL_HOST=db'
      - 'MYSQL_USER=root'
      - 'MYSQL_PASS=root'
    restart: unless-stopped
  db:
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root

