apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "helm.fullname" . }}-instabug-app-mysql
  labels:
    app: instabug-app-mysql
  {{- include "helm.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.instabugAppMysql.replicas }}
  selector:
    matchLabels:
      app: instabug-app-mysql
    {{- include "helm.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: instabug-app-mysql
      {{- include "helm.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - env:
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.kubernetesClusterDomain }}
        envFrom:
        - secretRef:
            name: {{ include "helm.fullname" . }}-app-sql-secret
        - secretRef:
            name: {{ include "helm.fullname" . }}-mysql-secret
        image: {{ .Values.instabugAppMysql.instabugAppMysql.image.repository }}:{{ .Values.instabugAppMysql.instabugAppMysql.image.tag
          | default .Chart.AppVersion }}
        imagePullPolicy: {{ .Values.instabugAppMysql.instabugAppMysql.imagePullPolicy }}
        name: instabug-app-mysql
        ports:
        - containerPort: 9090
          name: http
        resources: {}