apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "helm.fullname" . }}-mysql-pv-volume
  labels:
    app: instabug-mysql
    type: local
  {{- include "helm.labels" . | nindent 4 }}
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 5Gi
  hostPath:
    path: /mnt/data
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual