apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "helm.fullname" . }}-mysql-pv-claim
  labels:
    app: instabug-mysql
  {{- include "helm.labels" . | nindent 4 }}
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.pvc.mysqlPvClaim.storageRequest | quote }}
  storageClassName: {{ .Values.pvc.mysqlPvClaim.storageClass | quote }}