apiVersion: v1
kind: Secret
metadata:
  name: {{ include "helm.fullname" . }}-mysql-secret
  labels:
  {{- include "helm.labels" . | nindent 4 }}
stringData:
  MYSQL_ROOT_PASSWORD: {{ required "mysqlSecret.mysqlRootPassword is required" .Values.mysqlSecret.mysqlRootPassword
    | quote }}
type: Opaque