apiVersion: v1
kind: Service
metadata:
  name: {{ include "helm.fullname" . }}-instabug-mysql
  labels:
    app: instabug-mysql
  {{- include "helm.labels" . | nindent 4 }}
spec:
  type: {{ .Values.instabugMysql.type }}
  selector:
    app: instabug-mysql
    tier: mysql
  {{- include "helm.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.instabugMysql.ports | toYaml | nindent 2 -}}